In [1]:
import pandas as pd

In [2]:
json = pd.read_json('https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json')

In [3]:
json

,token,symbol,name,expiry,strike,lotsize,instrumenttype,exch_seg,tick_size
0,10412,KSHITIJPOL-BE,KSHITIJPOL,,-1,1,,NSE,1
1,8684,729RJ32-SG,729RJ32,,-1,100,,NSE,1
2,23546,75UK29-SG,75UK29,,-1,100,,NSE,1
3,4380,SENSEXIETF-BL,SENSEXIETF,,-1,1,,NSE,1
4,9360,1040UCL25-N4,1040UCL25,,-1,1,,NSE,1
...,...,...,...,...,...,...,...,...,...
115493,126089,GOLDM24AUG68500CE,GOLDM,29AUG2024,685000000,1,OPTFUT,NCO,5000
115494,125831,GOLD25MAR72200PE,GOLD,28MAR2025,722000000,1,OPTFUT,NCO,5000
115495,126044,GOLDM24OCT67500CE,GOLDM,29OCT2024,675000000,1,OPTFUT,NCO,5000
115496,126367,GOLDM24SEP68700CE,GOLDM,26SEP2024,687000000,1,OPTFUT,NCO,5000
115497,126911,GOLD25MAR79100CE,GOLD,28MAR2025,791000000,1,OPTFUT,NCO,5000

In [4]:
json.head(10)

,token,symbol,name,expiry,strike,lotsize,instrumenttype,exch_seg,tick_size
0,10412,KSHITIJPOL-BE,KSHITIJPOL,,-1,1,,NSE,1
1,8684,729RJ32-SG,729RJ32,,-1,100,,NSE,1
2,23546,75UK29-SG,75UK29,,-1,100,,NSE,1
3,4380,SENSEXIETF-BL,SENSEXIETF,,-1,1,,NSE,1
4,9360,1040UCL25-N4,1040UCL25,,-1,1,,NSE,1
5,24056,738HR34-SG,738HR34,,-1,100,,NSE,1
6,15178,TRIL-BE,TRIL,,-1,1,,NSE,5
7,5497,SFMP49DD-MF,SFMP49DD,,-1,1,,NSE,1
8,20655,898LTF29-N7,898LTF29,,-1,1,,NSE,1
9,12065,CYBERMEDIA-BL,CYBERMEDIA,,-1,1,,NSE,1

In [5]:
json.head(50)

,token,symbol,name,expiry,strike,lotsize,instrumenttype,exch_seg,tick_size
0,10412,KSHITIJPOL-BE,KSHITIJPOL,,-1,1,,NSE,1
1,8684,729RJ32-SG,729RJ32,,-1,100,,NSE,1
2,23546,75UK29-SG,75UK29,,-1,100,,NSE,1
3,4380,SENSEXIETF-BL,SENSEXIETF,,-1,1,,NSE,1
4,9360,1040UCL25-N4,1040UCL25,,-1,1,,NSE,1
5,24056,738HR34-SG,738HR34,,-1,100,,NSE,1
6,15178,TRIL-BE,TRIL,,-1,1,,NSE,5
7,5497,SFMP49DD-MF,SFMP49DD,,-1,1,,NSE,1
8,20655,898LTF29-N7,898LTF29,,-1,1,,NSE,1
9,12065,CYBERMEDIA-BL,CYBERMEDIA,,-1,1,,NSE,1
10,10336,797AP39-SG,797AP39,,-1,100,,NSE,1
11,2988,SANDESH-EQ,SANDESH,,-1,1,,NSE,5
12,2236,702HP36-SG,702HP36,,-1,100,,NSE,1
13,1896,661RJ31-SG,661RJ31,,-1,100,,NSE,1
14,24504,SATIPOLY-SM,SATIPOLY,,-1,1000,,NSE,5
15,16123,BHARATWIRE-EQ,BHARATWIRE,,-1,1,,NSE,5
16,4978,PHARMABEES-BL,PHARMABEES,,-1,1,,NSE,1
17,13950,LIQUID1-EQ,LIQUID1,,-1,1,,NSE,1
18,18400,744AP33-SG,744AP33,,-1,100,,NSE,1
19,3387,SMLISUZU-EQ,SMLISUZU,,-1,1,,NSE,5
20,3987,GREENPLY-EQ,GREENPLY,,-1,1,,NSE,5
21,27107,SPECIALITY-EQ,SPECIALITY,,-1,1,,NSE,1
22,18064,BPF02IGG-MF,BPF02IGG,,-1,1,,NSE,1
23,18946,747HR33A-SG,747HR33A,,-1,100,,NSE,1
24,12136,RADAAN-BL,RADAAN,,-1,1,,NSE,1
25,13981,SGBOCT27-GB,SGBOCT27,,-1,1,,NSE,1
26,11160,756TS40-SG,756TS40,,-1,100,,NSE,1
27,22422,677AP40-SG,677AP40,,-1,100,,NSE,1
28,17103,747TS41-SG,747TS41,,-1,100,,NSE,1
29,30326,ESSENTIA-BL,ESSENTIA,,-1,1,,NSE,1
30,19325,HISARMETAL-BL,HISARMETAL,,-1,1,,NSE,1
31,16918,ZFCVINDIA-BL,ZFCVINDIA,,-1,1,,NSE,5
32,24657,733MH44-SG,733MH44,,-1,100,,NSE,1
33,12976,MAHAPEXLTD-BL,MAHAPEXLTD,,-1,1,,NSE,1
34,6307,634RJ27-SG,634RJ27,,-1,100,,NSE,1
35,14774,111NSETEST-EQ,111NSETEST,,-1,1,,NSE,5
36,324,ANGELONE-EQ,ANGELONE,,-1,1,,NSE,5
37,15061,PSUBANK-EQ,PSUBANK,,-1,1,,NSE,1
38,17808,QUAL30IETF-EQ,QUAL30IETF,,-1,1,,NSE,1
39,19069,IIFLZC25-ND,IIFLZC25,,-1,1,,NSE,1
40,9604,772GS2049-GS,772GS2049,,-1,1,,NSE,1
41,23317,1025SCFL34-Z5,1025SCFL34,,-1,1,,NSE,1
42,18916,743RJ49-SG,743RJ49,,-1,100,,NSE,1
43,13859,VENUSREM-EQ,VENUSREM,,-1,1,,NSE,5
44,12259,BHARTIARTL-BL,BHARTIARTL,,-1,1,,NSE,5
45,3106,SFMP41DR-MF,SFMP41DR,,-1,1,,NSE,1
46,14635,766HR29-SG,766HR29,,-1,100,,NSE,1
47,12346,ELECTCAST-BL,ELECTCAST,,-1,1,,NSE,1
48,8054,KTKBANK-EQ,KTKBANK,,-1,1,,NSE,1
49,23363,MUTF27-NL,MUTF27,,-1,1,,NSE,1

In [12]:
json.tail(50)

,token,symbol,name,expiry,strike,lotsize,instrumenttype,exch_seg,tick_size
115448,127234,SILVER24SEP98000PE,SILVER,02SEP2024,980000000,1,OPTBLN,NCO,5000
115449,126984,ZINC24MAY257.5PE,ZINC,22MAY2024,2575000,1,OPTFUT,NCO,100
115450,126895,GOLD25JAN78100CE,GOLD,29JAN2025,781000000,1,OPTFUT,NCO,5000
115451,127742,SILVERM25APR103750PE,SILVERM,23APR2025,1037500000,1,OPTFUT,NCO,5000
115452,126153,GOLD25JAN76300PE,GOLD,29JAN2025,763000000,1,OPTFUT,NCO,5000
115453,125849,SILVERM24NOV84000PE,SILVERM,22NOV2024,840000000,1,OPTFUT,NCO,5000
115454,126537,NATURALGAS24OCT165PE,NATURALGAS,24OCT2024,1650000,1,OPTFUT,NCO,500
115455,127181,GOLD25JAN78700PE,GOLD,29JAN2025,787000000,1,OPTFUT,NCO,5000
115456,125687,GOLD25JAN71700PE,GOLD,29JAN2025,717000000,1,OPTFUT,NCO,5000
115457,126881,GOLD24NOV77200CE,GOLD,28NOV2024,772000000,1,OPTFUT,NCO,5000
115458,125827,GOLD24NOV72400PE,GOLD,28NOV2024,724000000,1,OPTFUT,NCO,5000
115459,125905,GOLD25MAY72400CE,GOLD,29MAY2025,724000000,1,OPTFUT,NCO,5000
115460,125919,GOLD25MAY73000PE,GOLD,29MAY2025,730000000,1,OPTFUT,NCO,5000
115461,126273,GOLD25MAR74000CE,GOLD,28MAR2025,740000000,1,OPTFUT,NCO,5000
115462,126830,COPPER24MAY865PE,COPPER,22MAY2024,8650000,1,OPTFUT,NCO,100
115463,126275,GOLD25MAR74100CE,GOLD,28MAR2025,741000000,1,OPTFUT,NCO,5000
115464,126012,SILVERM25FEB88250CE,SILVERM,21FEB2025,882500000,1,OPTFUT,NCO,5000
115465,126523,NATURALGAS24OCT130PE,NATURALGAS,24OCT2024,1300000,1,OPTFUT,NCO,500
115466,125742,GOLD24SEP70800CE,GOLD,26SEP2024,708000000,1,OPTFUT,NCO,5000
115467,127465,GOLD24NOV79500CE,GOLD,28NOV2024,795000000,1,OPTFUT,NCO,5000
115468,126250,GOLD25MAR72800PE,GOLD,28MAR2025,728000000,1,OPTFUT,NCO,5000
115469,126024,CRUDEOIL24AUG7150CE,CRUDEOIL,14AUG2024,71500000,1,OPTFUT,NCO,1000
115470,125768,GOLD25JAN72600CE,GOLD,29JAN2025,726000000,1,OPTFUT,NCO,5000
115471,126794,SILVERM25FEB91000PE,SILVERM,21FEB2025,910000000,1,OPTFUT,NCO,5000
115472,126415,SILVERM25JUN85500CE,SILVERM,23JUN2025,855000000,1,OPTFUT,NCO,5000
115473,126378,GOLDM24SEP69200PE,GOLDM,26SEP2024,692000000,1,OPTFUT,NCO,5000
115474,125877,CRUDEOIL24AUG7100PE,CRUDEOIL,14AUG2024,71000000,1,OPTFUT,NCO,1000
115475,126118,SILVERM25APR76750PE,SILVERM,23APR2025,767500000,1,OPTFUT,NCO,5000
115476,127142,GOLD24SEP77400CE,GOLD,26SEP2024,774000000,1,OPTFUT,NCO,5000
115477,126158,GOLD25JAN76600CE,GOLD,29JAN2025,766000000,1,OPTFUT,NCO,5000
115478,127232,SILVER24SEP97750PE,SILVER,02SEP2024,977500000,1,OPTBLN,NCO,5000
115479,125973,SILVERM24AUG93500CE,SILVERM,23AUG2024,935000000,1,OPTFUT,NCO,5000
115480,127170,GOLD24NOV78500CE,GOLD,28NOV2024,785000000,1,OPTFUT,NCO,5000
115481,125717,CRUDEOIL24SEP5400PE,CRUDEOIL,17SEP2024,54000000,1,OPTFUT,NCO,1000
115482,126957,SILVER24SEP93750PE,SILVER,02SEP2024,937500000,1,OPTBLN,NCO,5000
115483,126633,GOLD24NOV75900CE,GOLD,28NOV2024,759000000,1,OPTFUT,NCO,5000
115484,126875,GOLD24SEP76600CE,GOLD,26SEP2024,766000000,1,OPTFUT,NCO,5000
115485,125806,SILVERM25FEB84250CE,SILVERM,21FEB2025,842500000,1,OPTFUT,NCO,5000
115486,126607,GOLD24SEP74900CE,GOLD,26SEP2024,749000000,1,OPTFUT,NCO,5000
115487,126507,CRUDEOIL24AUG7950PE,CRUDEOIL,14AUG2024,79500000,1,OPTFUT,NCO,1000
115488,126519,NATURALGAS24OCT120PE,NATURALGAS,24OCT2024,1200000,1,OPTFUT,NCO,500
115489,127301,SILVERM24NOV93250PE,SILVERM,22NOV2024,932500000,1,OPTFUT,NCO,5000
115490,127210,GOLD25MAR79800CE,GOLD,28MAR2025,798000000,1,OPTFUT,NCO,5000
115491,126689,GOLD25MAR77900CE,GOLD,28MAR2025,779000000,1,OPTFUT,NCO,5000
115492,126327,GOLD25MAR76700CE,GOLD,28MAR2025,767000000,1,OPTFUT,NCO,5000
115493,126089,GOLDM24AUG68500CE,GOLDM,29AUG2024,685000000,1,OPTFUT,NCO,5000
115494,125831,GOLD25MAR72200PE,GOLD,28MAR2025,722000000,1,OPTFUT,NCO,5000
115495,126044,GOLDM24OCT67500CE,GOLDM,29OCT2024,675000000,1,OPTFUT,NCO,5000
115496,126367,GOLDM24SEP68700CE,GOLDM,26SEP2024,687000000,1,OPTFUT,NCO,5000
115497,126911,GOLD25MAR79100CE,GOLD,28MAR2025,791000000,1,OPTFUT,NCO,5000

In [13]:
json [['token', 'symbol','name']]

         token             symbol        name
0        10412      KSHITIJPOL-BE  KSHITIJPOL
1         8684         729RJ32-SG     729RJ32
2        23546          75UK29-SG      75UK29
3         4380      SENSEXIETF-BL  SENSEXIETF
4         9360       1040UCL25-N4   1040UCL25
...        ...                ...         ...
115493  126089  GOLDM24AUG68500CE       GOLDM
115494  125831   GOLD25MAR72200PE        GOLD
115495  126044  GOLDM24OCT67500CE       GOLDM
115496  126367  GOLDM24SEP68700CE       GOLDM
115497  126911   GOLD25MAR79100CE        GOLD

[115498 rows x 3 columns]